# Строки 

In [95]:
print('My name is {}'.format('Fred'))

My name is Fred


In [98]:
print('{name} написал {book}'.format(name='Swaroop', book='A Byte of Python'))


Swaroop написал A Byte of Python


In [99]:
age = 26
name = 'Swaroop'
print('Возраст {} -- {} лет.'.format(name, age))
print('Почему {} забавляется с этим Python?'.format(name))

Возраст Swaroop -- 26 лет.
Почему Swaroop забавляется с этим Python?


In [111]:
print('{0:.2}'.format(1/900))
print('{0:.2}'.format(1/3))

0.0011
0.33


In [125]:
'{0:^21}'.format('hello')

'        hello        '

In [126]:
s = '''Это многострочная строка.
Это вторая её строчка.'''
print(s)

Это многострочная строка.
Это вторая её строчка.


# Циклы

In [18]:
Condition = True #тип bool
u = 1
while Condition:
    print("uWu")
    if u % 10 == 0:
        break
    u += 1
    print('u=',u)
    continue #все равно не пашет
    print("You'll never see it")
    print('u=',u)

uWu
u= 2
uWu
u= 3
uWu
u= 4
uWu
u= 5
uWu
u= 6
uWu
u= 7
uWu
u= 8
uWu
u= 9
uWu
u= 10
uWu


In [159]:
number = 23
running = True
while running:
 guess = int(input('Введите целое число : '))
 if guess == number:
  print('Поздравляю, вы угадали.')
  running = False # это останавливает цикл while
 elif guess < number:
  print('Нет, загаданное число немного больше этого')
 else:
  print('Нет, загаданное число немного меньше этого.')
else:
 print('Цикл while закончен.')
# Здесь можете выполнить всё что вам ещё нужно

Введите целое число : 24
Нет, загаданное число немного меньше этого.
Введите целое число : 23
Поздравляю, вы угадали.
Цикл while закончен.


In [3]:
while True:
 s = input('Введите что-нибудь : ')
 if s=='exit':
  break
 if len(s) < 3:
  print('Слишком мало')
  continue
 else:
    print('Введённая строка достаточной длины')

Введите что-нибудь : sdfgfdg
Введённая строка достаточной длины
Введите что-нибудь : fg
Слишком мало
Введите что-нибудь : exit


# Структуры данных 

### Список

Список - изменяемый тип

In [1]:
# Это мой список покупок
shoplist = ['яблоки', 'манго', 'морковь', 'бананы']
print('Я должен сделать ', len(shoplist), 'покупок.')
print('Покупки:', end=' ')
for item in shoplist:
 print(item, end=' ')
print('\nТакже нужно купить риса.')
shoplist.append('рис')
print('Теперь мой список покупок таков:', shoplist)
print('Отсортирую-ка я свой список')
shoplist.sort()
print('Отсортированный список покупок выглядит так:', shoplist)
print('Первое, что мне нужно купить, это', shoplist[0])
olditem = shoplist[0]
del shoplist[0]
print('Я купил', olditem)
print('Теперь мой список покупок:', shoplist)

Я должен сделать  4 покупок.
Покупки: яблоки манго морковь бананы 
Также нужно купить риса.
Теперь мой список покупок таков: ['яблоки', 'манго', 'морковь', 'бананы', 'рис']
Отсортирую-ка я свой список
Отсортированный список покупок выглядит так: ['бананы', 'манго', 'морковь', 'рис', 'яблоки']
Первое, что мне нужно купить, это бананы
Я купил бананы
Теперь мой список покупок: ['манго', 'морковь', 'рис', 'яблоки']


In [ ]:
функции

In [ ]:
list.append(x)	Добавляет элемент в конец списка
list.extend(L)	Расширяет список list, добавляя в конец все элементы списка L
list.insert(i, x)	Вставляет на i-ый элемент значение x
list.remove(x)	Удаляет первый элемент в списке, имеющий значение x. ValueError, если такого элемента не существует
list.pop([i])	Удаляет i-ый элемент и возвращает его. Если индекс не указан, удаляется последний элемент
list.index(x, [start [, end]])	Возвращает положение первого элемента со значением x (при этом поиск ведется от start до end)
list.count(x)	Возвращает количество элементов со значением x
list.sort([key=функция])	Сортирует список на основе функции
list.reverse()	Разворачивает список
list.copy()	Поверхностная копия списка
list.clear()	Очищает список

### Кортеж

Кортеж - можно в круглых скобках, но это не обязательно. Неизменямый тип.

In [2]:
zoo = ('питон', 'слон', 'пингвин') # помните, что скобки не обязательны
print('Количество животных в зоопарке -', len(zoo))
new_zoo = 'обезьяна', 'верблюд', zoo
print('Количество клеток в зоопарке -', len(new_zoo))
print('Все животные в новом зоопарке:', new_zoo)
print('Животные, привезённые из старого зоопарка:', new_zoo[2])
print('Последнее животное, привезённое из старого зоопарка -', new_zoo[2][2])
print('Количество животных в новом зоопарке -', len(new_zoo)-1+len(new_zoo[2]))

Количество животных в зоопарке - 3
Количество клеток в зоопарке - 3
Все животные в новом зоопарке: ('обезьяна', 'верблюд', ('питон', 'слон', 'пингвин'))
Животные, привезённые из старого зоопарка: ('питон', 'слон', 'пингвин')
Последнее животное, привезённое из старого зоопарка - пингвин
Количество животных в новом зоопарке - 5


>Хотя скобки и не являются обязательными, я предпочитаю всегда указывать их, что-
бы было очевидно, что это кортеж, особенно в двусмысленных случаях. Например,
“print(1,2,3)” и “print( (1,2,3) )” делают разные вещи: первое выражение выводит
три числа, тогда как второе – кортеж, содержащий эти три числа.

>**Кортеж, содержащий 0 или 1 элемент**

>Пустой кортеж создаётся при помощи пустой пары скобок – “myempty = ()”. Однако, с кортежем из одного элемента не всё так просто. Его нужно указывать при помощи запятой после первого (и единственного) элемента, чтобы Python мог отличить кортеж от скобок, окружающих объект в выражении. Таким образом, чтобы получить кортеж, содержащий элемент 2, вам потребуется указать “singleton = (2,)”.

### Словарь

- Словарь – это некий аналог адресной книги.
Ключи (имена) связаны со значениями (информацией). 
Словарь: “d = {key1 : value1, key2 : value2 }”

>Ключ должен быть уникальным, могут использоваться только неизменяемые объекты (как строки), только простые объекты.
Значение - как неизменяемые, так и изменяемые объекты.пары ключ-значение никоим образом не упорядочены в словаре. Если вам необходим некоторый порядок, вам придётся отдельно отсортировать словарь перед об-
ращением к нему.

>Словари являются экземплярами/объектами класса dict.

In [11]:
ab = { 'Swaroop' : 'swaroop@swaroopch.com',
'Larry' : 'larry@wall.org',
'Matsumoto' : 'matz@ruby-lang.org',
'Spammer' : 'spammer@hotmail.com'
     }
print("Адрес Swaroop'а:", ab['Swaroop'])

# Удаление пары ключ-значение
del ab['Spammer']
print('\nВ адресной книге {0} контактов\n'.format(len(ab)))

#метод items возвращает список кортежей, далее пары ключ и значение присваиваем переменным name и address соответственно в цикле for..in
for name, address in ab.items():
 print('Контакт {0} с адресом {1}'.format(name, address))

# Добавление пары ключ-значение
ab['Guido'] = 'guido@python.org'
if 'Guido' in ab:
 print("\nАдрес Guido:", ab['Guido'])

Адрес Swaroop'а: swaroop@swaroopch.com

В адресной книге 3 контактов

Контакт Swaroop с адресом swaroop@swaroopch.com
Контакт Larry с адресом larry@wall.org
Контакт Matsumoto с адресом matz@ruby-lang.org

Адрес Guido: guido@python.org


### Последовательности

- arange

In [61]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [63]:
np.linspace(0, 2, 9)  # 9 чисел от 0 до 2 включительно

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [84]:
np.arange (1,4)

array([1, 2, 3])

In [86]:
a<30

array([ True,  True, False, False])

In [87]:
a+1


array([16, 21, 31, 56])

In [15]:
shoplist = ['яблоки', 'манго', 'морковь', 'бананы']
name = 'swaroop'
# Операция индексирования
print('Элемент 0 -', shoplist[0])
print('Элемент 1 -', shoplist[1])
print('Элемент 2 -', shoplist[2])
print('Элемент 3 -', shoplist[3])
print('Элемент -1 -', shoplist[-1])
print('Элемент -2 -', shoplist[-2])
print('Символ 0 -', name[0])
# Вырезка из списка
print('Элементы с 1 по 3:', shoplist[1:3])
print('Элементы с 2 до конца:', shoplist[2:])
print('Элементы с 1 по -1:', shoplist[1:-1])
print('Элементы от начала до конца:', shoplist[:])
print('Символы с 1 по 3:', name[1:3])
print('Символы с 2 до конца:', name[2:])
print('Символы с 1 до -1:', name[1:-1])
print('Символы от начала до конца:', name[:]) #двоеточие обязательно! 

Элемент 0 - яблоки
Элемент 1 - манго
Элемент 2 - морковь
Элемент 3 - бананы
Элемент -1 - бананы
Элемент -2 - морковь
Символ 0 - s
Элементы с 1 по 3: ['манго', 'морковь']
Элементы с 2 до конца: ['морковь', 'бананы']
Элементы с 1 по -1: ['манго', 'морковь']
Элементы от начала до конца: ['яблоки', 'манго', 'морковь', 'бананы']
Символы с 1 по 3: wa
Символы с 2 до конца: aroop
Символы с 1 до -1: waroo
Символы от начала до конца: swaroop


>полученная вырезка будет начинаться с указанной начальной позиции,
а заканчиваться прямо перед указанной конечной позицией, т.е. начальная
позиция будет включена в вырезку, а **конечная – нет.**

In [ ]:
шаг вырезки (по умолчанию шаг вырезки равен 1):

In [24]:
shoplist = ['яблоки', 'манго', 'морковь', 'бананы']

print ('шаг 1:', shoplist[::1])

print ('шаг 2:', shoplist[::2], '(элементы, находящиеся на позициях 0, 2,..)')

print ('шаг 3:', shoplist[::3], '(элементы, находящиеся на позициях 0, 3,..)')

print ('обратный порядок:', shoplist[::-1])

шаг 1: ['яблоки', 'манго', 'морковь', 'бананы']
шаг 2: ['яблоки', 'морковь'] (элементы, находящиеся на позициях 0, 2,..)
шаг 3: ['яблоки', 'бананы'] (элементы, находящиеся на позициях 0, 3,..)
обратный порядок: ['бананы', 'морковь', 'манго', 'яблоки']


### Множества 

In [25]:
>>> bri = set(['Бразилия', 'Россия', 'Индия'])
>>> 'Индия' in bri
True
>>> 'США' in bri
False
>>> bric = bri.copy()
>>> bric.add('Китай') 
>>> bric.issuperset(bri)
True
>>> bri.remove('Россия')
>>> bri & bric # OR bri.intersection(bric)
{'Бразилия', 'Индия'}

{'Бразилия', 'Индия'}

# Numpy

### Создать массив

- np.array (много переменных)
- np.empty (две переменных)
- np.eye (две переменных)
- np.ones (3 переменных - еще количество массивов в начале)

In [28]:
import numpy as np
>>> a = np.array([15, 20, 30, 55])
>>> a

array([15, 20, 30, 55])

In [27]:
>>> type(a)

numpy.ndarray

In [6]:
b=np.array ([[0,6,7,8,9],[4,5,6,7,8],[34,5,6,6,6]], dtype=np.complex)
print('{}'.format(b))
type(b)

[[ 0.+0.j  6.+0.j  7.+0.j  8.+0.j  9.+0.j]
 [ 4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j]
 [34.+0.j  5.+0.j  6.+0.j  6.+0.j  6.+0.j]]


numpy.ndarray

In [148]:
c=np.array((2,3,5))
c

array([2, 3, 5])

In [56]:
np.eye(4,5)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
np.empty((3, 3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.62047965e-321],
       [6.01334412e-154, 6.01346930e-154, 1.28448405e-057]])

In [29]:

b=np.ones((3, 2, 1),dtype=np.integer)
b

array([[[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]]])

In [ ]:
Заполнение массива одинаковым значением

In [118]:
import numpy as np
c = np.array([1, 2, 3], float)
c

array([1., 2., 3.])

In [119]:
c.fill(0)
c

array([0., 0., 0.])

### Команды: работа с массивами 

**Петля для массива: np.fromfucntion (f, (a,b))**

In [31]:
def f1(i,j):
    return 3*i+j
b = np.fromfunction(f1, (40,30))
b

array([[  0.,   1.,   2., ...,  27.,  28.,  29.],
       [  3.,   4.,   5., ...,  30.,  31.,  32.],
       [  6.,   7.,   8., ...,  33.,  34.,  35.],
       ...,
       [111., 112., 113., ..., 138., 139., 140.],
       [114., 115., 116., ..., 141., 142., 143.],
       [117., 118., 119., ..., 144., 145., 146.]])

**Другие команды**

In [33]:
a = np.array([[1, 2, 3], [4, 5, 6]])
#np.sum(a)
print(a.sum())
print(np.sum(a))
print(a.min())
print(a.max())

print (a.min(axis=0))  # Наименьшее число в каждом столбце
print (a.min(axis=1))  # Наименьшее число в каждой строке

21
21
1
6
[1 2 3]
[1 4]


**Математические операции над массивами**


In [142]:
>>> a = np.array([1,2,3], float)
>>> b = np.array([5,2,6], float)
>>> a + b

array([6., 4., 9.])

In [141]:
a-b

array([-4.,  0., -3.])

In [138]:
a * b

array([ 5.,  4., 18.])

In [135]:
b / a

array([5., 1., 2.])

In [136]:
a % b

array([1., 0., 3.])

In [137]:
b**a

array([  5.,   4., 216.])

>могут быть применены поэлементно к массивам. Собственно функции: abs, sign, sqrt, log, log10, exp, sin, cos, tan, arcsin, arccos, arctan, sinh, cosh, tanh, arcsinh, arccosh, и arctanh.

In [143]:
a = np.array([1, 4, 9], float)
np.sqrt(a)

array([1., 2., 3.])

**Функции floor, ceil и rint возвращают нижние, верхние или ближайшие (округлённое) значение:**

In [ ]:
>>> a = np.array([1.1, 1.5, 1.9], float)
>>> np.floor(a)
array([ 1.,  1.,  1.])
>>> np.ceil(a)
array([ 2.,  2.,  2.])
>>> np.rint(a)
array([ 1.,  2.,  2.])

**Важные математические константы:**

In [146]:
print ('число пи:',np.pi)

print ('число эйлера:', np.e)


число пи: 3.141592653589793
число эйлера: 2.718281828459045


**Полиномы**

In [157]:
import numpy as np 
np.roots([1,-1,-5]) #возвращает корни от этого полинома 

np. poly ([1,3,4,5,6]) #возвращает полином от этих корней

np.polyder([1./4., 1./3., 1./2., 1., 0.])  #производная 
    
np.polyint([1, 1, 1, 1])    # интеграл 

array([   1.,  -19.,  137., -461.,  702., -360.])

### Индексы, срезы, итерации

Итерация в программировании — в широком смысле — организация обработки данных, при которой действия повторяются многократно, не приводя при этом к вызовам самих себя. В узком смысле — один шаг итерационного, циклического процесса.

In [40]:
a = np.arange(10) ** 3
print (a[1])
print (a[3:7])

#замена:
a[3:7] = 8
print (a)

#реверс:
print (a[::-1])

#удаление: удалять кажется нельзя
#del a[4]

for i in a:
 print(i ** (1/3))

1
[ 27  64 125 216]
[  0   1   8   8   8   8   8 343 512 729]
[729 512 343   8   8   8   8   8   1   0]
0.0
1.0
2.0
2.0
2.0
2.0
2.0
6.999999999999999
7.999999999999999
8.999999999999998


In [65]:
import numpy as np
b = np.array([[  0, 1, 2, 3],
               [10, 11, 12, 13],
               [20, 21, 22, 23],
               [30, 31, 32, 33],
               [40, 41, 42, 43]])

print (b[2,3])  # 2 строка, 4 столбец
print (b[(2,3)])
print (b[2][3])  # Можно и так
print ('третий столбец')
print (b[:,2])  # Третий столбец
print ('первые две строчки')
print (b[:2,:])  # Первые две строки
print ('вторая и третья строчки')
print (b[1:3,:])  # Вторая и третья строки


23
23
23
третий столбец
[ 2 12 22 32 42]
первые две строчки
[[ 0  1  2  3]
 [10 11 12 13]]
вторая и третья строчки
[[10 11 12 13]
 [20 21 22 23]]


In [67]:
a= np.array ([[4,5,6,8,9], [4,5,7,8,3],[6,2,8,0,4]])
a

array([[4, 5, 6, 8, 9],
       [4, 5, 7, 8, 3],
       [6, 2, 8, 0, 4]])

**Метод shape** возвращает количество строк и столбцов в матрице:

In [82]:
a.shape

(3, 5)

**Метод dtype** возвращает тип переменных, хранящихся в массиве:

In [83]:
a.dtype

dtype('int32')

**Метод len** возвращает длину первого измерения (оси):

In [88]:
ab = np.array ([[4,5,6], [4,5,6]])
len(ab)

2

**Метод in** используется для проверки на наличие элемента в массиве:

In [89]:
>>> a = np.array([[1, 2, 3], [4, 5, 6]], float)
>>> 2 in a

True

In [90]:
>>> 0 in a

False

**Копирование массива** 

In [93]:
a = np.array([1, 2, 3], float)
b = a
c =  a.copy()
a[0]= 0
print ('a: ', a)
print ('b: ', b)
print ('c: ', c)

a:  [0. 2. 3.]
b:  [0. 2. 3.]
c:  [1. 2. 3.]


**Изменение формы массива** 

In [95]:
a = np.array(range(10), float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [98]:
a = a.reshape((5, 2))
print (a)
a.shape


[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


(5, 2)

**Cписки с массивов**

In [111]:
a = np.array([[1, 2, 3],[2,7,4]],  float)

a.tolist()
list(a)

[array([1., 2., 3.]), array([2., 7., 4.])]

In [112]:
list (a)

[array([1., 2., 3.]), array([2., 7., 4.])]

Многомерный массив можно **переконвертировать в одномерный** при помощи метода flatten:

In [121]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print (a)

a.flatten()


[[1. 2. 3.]
 [4. 5. 6.]]


array([1., 2., 3., 4., 5., 6.])

**Транспонирование массивов** также возможно, при этом создается новый массив:


In [123]:
a = np.array(range(6), float).reshape((2, 3))
print(a)

a.transpose()


[[0. 1. 2.]
 [3. 4. 5.]]


array([[0., 3.],
       [1., 4.],
       [2., 5.]])

**Конкатенация массивов**

>Конкатена́ция — операция склеивания объектов линейной структуры, обычно строк.

In [125]:
a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)
np.concatenate((a, b, c))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Случайные числа 

In [168]:
import numpy as np
np.random.seed(1337)

def czbkhunxjc(s):
    s = 82+42+s
    return(s)
t = np.random.uniform(low=3, high=5, size=10)
w = 85
def aumsbgkcck(i):
    i = 65+i
    return(i)
t = 23
def thzfgfqslf(m):
    m = 41-m
    return(m)
def soiazawbpo(d):
    d = 46/46-d
    return(d)
def vsjyiqxzuu(l):
    l = 31*l
    return(l)
def tflhgvgugt(m):
    m = 95+4*m
    return(m)
w = 46
print(np.round([thzfgfqslf(w) for w in w], 1))

[27.2 28.  28.7 23.  30.8 22.  27.8 31.3 36.2 24.5]


In [161]:
help(np.round) 


Help on function round_ in module numpy:

round_(a, decimals=0, out=None)
    Round an array to the given number of decimals.
    
    See Also
    --------
    around : equivalent function; see for details.



In [ ]:
from ludwig.api import *

model_definition = {
    "input_features": [ 
        {"name": "age", "type": "numerical"}, 
________________________ПРОПУЩЕНО________________________

________________________ПРОПУЩЕНО________________________

        {"name": "proportion", "type": "numerical"}, 
        {
            "name": "photo", "type": "image",  
            "preprocessing": {
                "height": 256, "width": 256  
            }
        },
        {
            "name": "lnc_RNA_sequence", "type": "text",  
            "preprocessing": {
                "encoder": "rnn",  
________________________ПРОПУЩЕНО________________________

________________________ПРОПУЩЕНО________________________

________________________ПРОПУЩЕНО________________________

            }
        },
    ],
    "output_features": [ 
        {"name": "target", "type": "category"} 
    ]
}
model = LudwigModel(model_definition)
train_stats = model.train(df) 
model.save("ludwig_model")